name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25
      - name: Get Kobra package name
        run: echo "KOBRA_PKG_NAME=$(grep '^PKG_NAME' Makefile | cut -d '=' -f 2)" >> $GITHUB_ENV
      - name: Get Kobra version
        run: echo "KOBRA_VERSION=$(grep '^VERSION' Makefile | cut -d '=' -f 2)" >> $GITHUB_ENV
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_NAME: ${{ env.KOBRA_PKG_NAME }}
          VERSION: ${{ env.KOBRA_VERSION }}
      - name: Retrieve Darwin ARM64 SHA256 checksum
        run: echo "DARWIN_ARM64_SHA256=$(sha256sum dist/kobra_darwin_arm64_v8.0/kobra | cut -d ' ' -f 1)" >> $GITHUB_ENV
      - name: Retrieve Darwin AMD64 SHA256 checksum
        run: echo "DARWIN_AMD64_SHA256=$(sha256sum dist/kobra_darwin_amd64_v1/kobra | cut -d ' ' -f 1)" >> $GITHUB_ENV
      - name: Retrieve Linux ARM64 SHA256 checksum
        run: echo "LINUX_ARM64_SHA256=$(sha256sum dist/kobra_linux_arm64_v8.0/kobra | cut -d ' ' -f 1)" >> $GITHUB_ENV
      - name: Retrieve Linux AMD64 SHA256 checksum
        run: echo "LINUX_AMD64_SHA256=$(sha256sum dist/kobra_linux_amd64_v1/kobra | cut -d ' ' -f 1)" >> $GITHUB_ENV
      - name: Read homebrew Formulae template
        id: homebrew
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: kobra.rb.tmpl
      - name: Display Homebrew Formulae
        run: echo "${{ steps.homebrew.outputs.content }}"
      # - run: sudo apt-get -y install debhelper
      # - name: Build Debian package
      #   run: make deb
      # - name: Release Debian Package
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: |
      #       ../*.deb
