name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25
      - name: Get Kobra package name
        run: echo "KOBRA_PKG_NAME=$(grep '^PKG_NAME' Makefile | cut -d '=' -f 2)" >> $GITHUB_ENV
      - name: Get Kobra version
        run: echo "KOBRA_VERSION=$(grep '^VERSION' Makefile | cut -d '=' -f 2)" >> $GITHUB_ENV
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_NAME: ${{ env.KOBRA_PKG_NAME }}
          VERSION: ${{ env.KOBRA_VERSION }}
      - name: Retrieve build residues SHA256 checksums
        run: |
          sudo apt-get -y install curl
          curl -L https://github.com/kowabunga-cloud/kobra/releases/download/${{ env.KOBRA_VERSION }}/kobra_${{ env.KOBRA_VERSION }}_SHA256SUMS -o cksum.txt
          echo "DARWIN_ARM64_SHA256=$(cat cksum.txt | grep darwin_arm64 | head -1 | cut -d ' ' -f 1)" >> $GITHUB_ENV
          echo "DARWIN_AMD64_SHA256=$(cat cksum.txt | grep darwin_amd64 | head -1 | cut -d ' ' -f 1)" >> $GITHUB_ENV
          echo "LINUX_ARM64_SHA256=$(cat cksum.txt | grep linux_arm64 | head -1 | cut -d ' ' -f 1)" >> $GITHUB_ENV
          echo "LINUX_AMD64_SHA256=$(cat cksum.txt | grep linux_amd64 | head -1 | cut -d ' ' -f 1)" >> $GITHUB_ENV
      - name: Build Homebrew Formulae
        run: |
          FORMULAE="class Kobra < Formula
            desc \"DevOps deployment swiss-army knife utility\"
            homepage \"https://github.com/kowabunga-cloud/kobra/\"
            version \"${{ env.KOBRA_VERSION }}\"

            if OS.mac?
              if Hardware::CPU.intel?
                url \"https://github.com/kowabunga-cloud/kobra/releases/download/${{ env.KOBRA_VERSION }}/kobra_${{ env.KOBRA_VERSION }}_darwin_amd64.tar.gz\"
                sha256 \"${{ env.DARWIN_AMD64_SHA256 }}\"
              elsif Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
                url \"https://github.com/kowabunga-cloud/kobra/releases/download/${{ env.KOBRA_VERSION }}/kobra_${{ env.KOBRA_VERSION }}_darwin_arm64.tar.gz\"
                sha256 \"${{ env.DARWIN_ARM64_SHA256 }}\"
              end
            elsif OS.linux?
              if Hardware::CPU.intel?
                url \"https://github.com/kowabunga-cloud/kobra/releases/download/${{ env.KOBRA_VERSION }}/kobra_${{ env.KOBRA_VERSION }}_linux_amd64.tar.gz\"
                sha256 \"${{ env.LINUX_AMD64_SHA256 }}\"
              elsif Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
                url \"https://github.com/kowabunga-cloud/kobra/releases/download/${{ env.KOBRA_VERSION }}/kobra_${{ env.KOBRA_VERSION }}_linux_arm64.tar.gz\"
                sha256 \"${{ env.LINUX_ARM64_SHA256 }}\"
              end
            end

            def install
              bin.install \"kobra\"
            end
          end
          "
          echo "$FORMULAE" > kobra.rb
      - name: Push Formula to Homebrew tap
        run: |
          git clone https://github.com/kowabunga-cloud/homebrew-tap.git
          cd homebrew-tap

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          mv ../kobra.rb .
          git add ./kobra.rb
          git commit -m "Update formula for ${{ env.KOBRA_VERSION }}"
          git push https://x-access-token:${{ secrets.PAT_HOMEBREW_TAP_RELEASER }}@github.com/kowabunga-cloud/homebrew-tap.git HEAD:master
      - run: sudo apt-get -y install debhelper
      - name: Build Debian package
        run: make deb
      - name: Release Debian Package
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ../*.deb
      - name: Trigger APT repository update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: '${{ secrets.PAT_PACKAGES_WORKFLOW_TOKEN }}'
          repository: kowabunga-cloud/packages
          event-type: Publish-Deb
