name: Go Security Checks
on:
  push:
    branches:
      - master

jobs:
  gosec:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25
      - name: Run Gosec Security Scanner
        run: make sec
